#pragma once

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include "core/geometry.hpp"

namespace mepwm::core {

// Opaque, platform-assigned window handle. Stable for the lifetime of the
// window (an X11 Window, a registry slot for a macOS AXUIElement, an HWND).
using WindowId = std::uint64_t;
constexpr WindowId kNoWindow = 0;

struct WindowInfo {
  WindowId id = kNoWindow;
  std::string application;
  std::string title;
  Rect frame;
};

// Engine-level commands. The engine decides which hotkey maps to which
// action (policy); the platform only translates key names to native codes
// and reports presses (mechanism).
enum class Action {
  FocusLeft,
  FocusDown,
  FocusUp,
  FocusRight,
  SwapLeft,
  SwapDown,
  SwapUp,
  SwapRight,
  ResizeLeft,   // move the nearest matching split boundary in that direction
  ResizeDown,
  ResizeUp,
  ResizeRight,
  SplitVertical,    // side-by-side columns (X11 Super+v)
  SplitHorizontal,  // stacked rows (X11 Super+s)
  NextTab,
  PrevTab,
  MergePane,        // absorb the sibling pane's windows as tabs
  ShrinkMaster,     // in the tree layout: shrink the selected pane's split
  GrowMaster,
  Retile,
  SpawnTerminal,
  OpenAppPicker,
  OpenProjectPicker,        // all known projects (X11 Super+i)
  OpenActiveProjectPicker,  // only projects that hold windows (X11 Super+o)
  OpenThemePicker,          // fuzzy picker over the theme palettes (X11 Super+Shift+t)
  OpenWallpaperPicker,      // fuzzy picker over the wallpaper dirs (X11 Super+Shift+w)
  ToggleHelpPanel,
  ToggleTodoPanel,
  ToggleHints,  // Vimium-style click-hint overlay (X11 Super+f)
  ToggleBars,   // hide/show all border chrome and reclaim its space (X11 Super+b)
  SwitchWorkspace,  // argument = workspace number (1-based)
  SendToWorkspace,  // argument = workspace number (1-based)
  Quit,
};

// N1..N9 must stay contiguous: workspace bindings are generated by offset.
enum class Key { B, D, F, H, I, J, K, L, M, N, O, P, R, S, T, V, W, Return, Q, Minus, Equal, Slash, Tab, N1, N2, N3, N4, N5, N6, N7, N8, N9 };

// What kModPrimary resolves to; chosen by Config::modifier ("cmd", "alt",
// "ctrl", "super", "fn", "fn+cmd") and translated to a native mask by each
// platform. Fn is the Globe/fn key and FnCmd is the Globe/fn key held
// together with Command; both are only meaningful on macOS.
enum class Modifier { Alt, Cmd, Ctrl, Super, Fn, FnCmd };

constexpr unsigned int kModPrimary = 1U << 0U;
constexpr unsigned int kModShift = 1U << 1U;
constexpr unsigned int kModCtrl = 1U << 2U;

struct Hotkey {
  unsigned int modifiers = kModPrimary;
  Key key = Key::H;
};

// A focus/normal border ring the platform draws around a managed window
// (overlay platforms use click-through native windows for this, standing in
// for the X11 backend's window borders).
struct Border {
  Rect frame;                    // the managed window's frame; ring drawn around it
  unsigned int width = 2;
  std::string color = "#444444"; // "#rrggbb"
};

struct BarCell {
  BarCell() = default;
  BarCell(std::string cell_text, bool cell_highlight = false, std::string cell_id = {},
          std::string cell_color = {})
      : text(std::move(cell_text)), highlight(cell_highlight), id(std::move(cell_id)),
        color(std::move(cell_color)) {}

  std::string text;
  bool highlight = false;
  // Stable identifier reported back in ChromeClicked events ("volume",
  // "wifi", a window index, ...); empty cells are not clickable.
  std::string id;
  // Optional "#rrggbb" fill: the platform paints it as the cell background
  // and draws the text in the chrome background color (the X11 backend's
  // filled-pill style, e.g. the red/green active-TODO pill).
  std::string color;
};

// Which chrome panel a click landed in.
enum class ChromeArea { TopBar, BottomBar, LeftDock, RightDock, SidePanel, TabBar };

// A key press delivered to a keyboard-grabbing side panel (todo navigation,
// contextual help). Printable input arrives as Character with Event::text
// holding the typed glyphs and Event::ctrl the Control state (^n/^p).
enum class PanelKey { Character, Escape, Return, Backspace, Up, Down };

// One row of the generic fuzzy list picker (show_list_picker). The engine
// supplies content (policy); the platform renders, filters, and reports the
// choice back (mechanism).
struct PickerItem {
  std::string id;     // reported in the PickerSelected event
  std::string label;  // shown and fuzzy-matched
};

// The strip of tab cells above a pane holding more than one window.
struct TabBar {
  Rect frame;
  std::vector<BarCell> tabs;  // id = the tab's WindowId as a string
};

// System mutations the engine can request when a panel row is clicked; the
// platform maps them to native calls (osascript, TIS, player scripting).
enum class SystemAction {
  SetOutputVolume,       // value = percent
  SetInputVolume,        // value = percent
  SetOutputMuted,        // value = 0/1
  ToggleAppearance,      // dark <-> light
  SelectKeyboardLayout,  // argument = layout name
  SetWallpaper,          // argument = image file path; applied to every screen
  MediaPrevious,
  MediaPlayPause,
  MediaNext,
};

// Screen-edge chrome: the overlay analogue of the X11 backend's top bar,
// side docks, and bottom widget bar. The engine decides geometry and
// content (policy); the platform only renders panels and text (mechanism).
struct Chrome {
  // False while the mod+b toggle has the border chrome hidden: the platform
  // orders all four edge panels out instead of laying them out.
  bool visible = true;
  Rect top;
  Rect bottom;
  Rect left;
  Rect right;
  std::string top_left;
  // Workspace cells drawn after top_left; click reports the cell id.
  std::vector<BarCell> top_cells;
  std::string top_center;
  std::string top_right;
  std::string bottom_text;
  std::vector<BarCell> left_cells;
  std::vector<BarCell> right_cells;
  // System widgets, drawn right-aligned in the bottom bar.
  std::vector<BarCell> bottom_widgets;
  // Left-aligned bottom-bar cells: with a color they render as filled pills
  // (the active-TODO pill), colorless ones as plain bar text (the OS icon);
  // bottom_text renders in whatever space is left between the two groups.
  std::vector<BarCell> bottom_left_widgets;
  std::string background_color = "#1d1f21";
  std::string text_color = "#d8dee9";
  std::string accent_color = "#5294e2";
};

struct Event {
  enum class Type {
    // The set of manageable windows changed (created/destroyed/appeared).
    // The engine re-lists and reconciles; the platform does not need to say
    // which window changed.
    WindowsChanged,
    FocusChanged,
    ScreenChanged,
    ActionTriggered,
    // Periodic heartbeat from the platform's event loop (~0.5s); drives
    // clock/status refreshes in the chrome.
    Tick,
    // A chrome cell was clicked; `area` and `cell` identify it.
    ChromeClicked,
    // Enter was pressed in the list picker: `cell` is the selected item's id
    // (empty when nothing matched) and `text` the raw typed query.
    PickerSelected,
    // The list picker's highlighted row changed (arrows or refiltering):
    // `cell` is the highlighted item's id, empty when nothing matches. Lets
    // the engine live-preview the highlighted choice (theme picker).
    PickerHighlighted,
    // The list picker closed without a selection (Escape, or toggled
    // closed); the engine reverts any live preview.
    PickerCancelled,
    // A key press reached a side panel marked wants_keys; `panel_key`,
    // `ctrl`, and (for Character) `text` describe it.
    PanelKeyPressed,
  };
  Type type = Type::WindowsChanged;
  Action action = Action::Retile;   // valid when type == ActionTriggered
  int argument = 0;                 // the argument register_hotkey() was given
  WindowId window = kNoWindow;      // valid when type == FocusChanged
  ChromeArea area = ChromeArea::BottomBar;  // valid when type == ChromeClicked
  std::string cell;                 // valid when type == ChromeClicked / PickerSelected
  std::string text;                 // valid when type == PickerSelected / PanelKeyPressed
  PanelKey panel_key = PanelKey::Character;  // valid when type == PanelKeyPressed
  bool ctrl = false;                         // valid when type == PanelKeyPressed
};

// A running AI coding agent (claude/codex), matching the X11 backend's
// AgentStatus: merged from mwm-agents status files (read by the engine) and
// a platform-side process scan.
struct AgentInfo {
  std::string kind;    // "claude", "codex", ...
  std::string status;  // "running", "needs_input", ...
  std::string cwd;
  std::string label;
  bool needs_input = false;
};

// System facts for the bottom-bar widgets. A field keeps its sentinel when
// the platform cannot determine it (no battery, missing permission, ...).
struct SystemStatus {
  int battery_percent = -1;
  bool battery_charging = false;
  int battery_minutes_remaining = -1;  // to empty (or full when charging)
  bool wifi_on = false;
  std::string wifi_ssid;         // may stay empty when on (macOS gates the
                                 // SSID behind the Location permission)
  int volume_percent = -1;
  bool volume_muted = false;
  int input_volume_percent = -1; // microphone
  bool bluetooth_on = false;
  std::string bluetooth_device;  // first connected device, if any
  std::vector<BarCell> bluetooth_devices;  // paired list; highlight = connected
  double load_average = -1.0;
  // Whole-machine CPU usage since the previous sample (the X11 backend's
  // /proc/stat-delta number); -1 until two samples exist.
  int cpu_used_percent = -1;
  int memory_used_percent = -1;
  int disk_used_percent = -1;
  std::string media_title;       // "artist - title" of the playing track
  std::string keyboard_layout;   // current input source name
  std::vector<BarCell> keyboard_layouts;  // selectable; highlight = current
  std::string appearance;        // "dark" / "light"
  std::string git_branch;        // of the launch directory, if a repo
  int git_dirty = -1;            // changed-file count; -1 = not a repo
  std::vector<std::string> git_status_lines;  // porcelain output, capped
  std::vector<AgentInfo> agents;  // process-scanned agents (no status files)
};

// A toggleable overlay sidebar (todo list, help, ...). Content is engine
// policy; the platform renders the panel.
struct SidePanel {
  bool visible = false;
  Rect frame;
  std::string title;
  std::vector<BarCell> lines;
  // Centered hint drawn below a separator at the panel's bottom edge
  // ("?  Toggle help"); empty means no footer strip.
  std::string footer;
  // The platform should give the panel keyboard focus while visible and
  // report presses as PanelKeyPressed events (the overlay analogue of the
  // X11 backend's keyboard grab for actionable panels).
  bool wants_keys = false;
};

// The bridge implementor: everything a host platform must provide for the
// shared TilingEngine to manage windows on it. Implementations live in
// src/macos, src/windows, ... and must not leak platform types here.
class Platform {
 public:
  Platform() = default;
  virtual ~Platform() = default;
  Platform(const Platform&) = delete;
  Platform& operator=(const Platform&) = delete;
  Platform(Platform&&) = delete;
  Platform& operator=(Platform&&) = delete;

  // Acquires platform prerequisites (e.g. the macOS Accessibility trust
  // prompt). `primary` is what kModPrimary means in every Hotkey that will
  // be registered. Returns false and fills *error when the engine cannot
  // start.
  virtual bool initialize(Modifier primary, std::string* error) = 0;

  // Primary-screen area available for tiling (menu bars/docks excluded),
  // in a top-left-origin coordinate system shared with WindowInfo::frame.
  virtual Rect work_area() = 0;

  // Current manageable windows (standard, non-minimized), any order.
  virtual std::vector<WindowInfo> list_windows() = 0;

  virtual WindowId focused_window() = 0;
  virtual void set_window_frame(WindowId window, const Rect& frame) = 0;
  virtual void focus_window(WindowId window) = 0;
  // Brings the window to the front of its stacking context WITHOUT giving
  // it input focus (used to keep a pane's active tab on top).
  virtual void raise_window(WindowId window) = 0;

  // Returns false when the hotkey could not be bound (already taken, ...).
  // `argument` is echoed back in the ActionTriggered event (e.g. the
  // workspace number).
  virtual bool register_hotkey(const Hotkey& hotkey, Action action, int argument = 0) = 0;

  // Replaces all currently drawn borders with `borders` (empty clears them).
  virtual void update_borders(const std::vector<Border>& borders) = 0;

  // Redraws the screen-edge bar panels.
  virtual void update_chrome(const Chrome& chrome) = 0;

  // Shows, updates, or hides (visible == false) the overlay sidebar.
  virtual void update_side_panel(const SidePanel& panel) = 0;

  // Replaces all pane tab bars (empty hides them all).
  virtual void update_tab_bars(const std::vector<TabBar>& bars) = 0;

  // True when the platform renders chrome text with a font that covers the
  // Nerd Font glyph range (core/icons.hpp); the engine then uses icons
  // instead of text prefixes in widgets.
  virtual bool has_icon_font() = 0;

  // Samples system facts for the widgets. May be slow-ish (subprocesses);
  // the engine calls it on a coarse cadence, not per frame.
  virtual SystemStatus system_status() = 0;

  // Executes a panel-row action synchronously; the engine resamples
  // system_status() right after, so implementations must not return before
  // the change is applied.
  virtual void perform(SystemAction action, int value = 0, const std::string& argument = {}) = 0;

  virtual void spawn(const std::string& shell_command) = 0;

  // Shows/hides the platform's application picker overlay (the analogue of
  // the X11 backend's Super+p launcher). Which applications exist and how to
  // launch one is platform mechanism, so the whole picker lives behind this
  // toggle rather than in the engine.
  virtual void toggle_app_picker() = 0;

  // Toggles the Vimium-style click-hint overlay (the X11 backend's Super+f):
  // a letter chip on every clickable chrome cell; typing a chip's label
  // replays the same ChromeClicked event a real click there would produce.
  // Entirely platform mechanism because only the renderer knows where its
  // cells ended up on screen.
  virtual void toggle_hints() = 0;

  // Shows the generic fuzzy list picker over `items`. Called again with the
  // same `title` while it is showing, it closes instead (toggle); a
  // different title or the app picker replaces the current picker. Enter
  // emits a PickerSelected event; Escape emits PickerCancelled; highlight
  // changes emit PickerHighlighted. A non-empty `selected_id` names the item
  // to highlight initially (instead of the first row).
  virtual void show_list_picker(const std::string& title, const std::vector<PickerItem>& items,
                                const std::string& selected_id = {}) = 0;

  // Blocks running the native event loop, invoking on_event for each event
  // until stop() is called (typically from inside on_event).
  virtual void run(const std::function<void(const Event&)>& on_event) = 0;
  virtual void stop() = 0;
};

}  // namespace mepwm::core
